###抛出错误
与`try-catch`语句相配的还有一个`throw`操作符,用于随时抛出自定义错误.抛出错误时,必须要给`throw`操作符指定一个值,该值什么类型,没有要求

```javascript
throw 12345
throw 'Hello world!'
throw true
throw {name: "JS"}
throw new Error('Something bad happened')
throw new RangeError('Something bad happened')
```

在遇到`throw`操作符时,代码会立即停止执行.仅当有`try-catch`语句捕获到被抛弃的值时,代码才会继续执行